config/routes.rb
BerkTest::Application.routes.draw do
  resources :orders

  get '/employees/avg_prices' => 'employees#avg_prices'
  get '/employees/last_30' => 'employees#last_30'
  resources :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :orders

  def avg_unit_price_30
    num_orders = 0
    avg = 0.0
    self.orders.where('created_at > ?', DateTime.now - 30.days).each do |o|
      num_orders += 1
      avg += o.total_price / o.num_units
    end
    num_orders == 0 ? 'N/A' : (avg / num_orders).to_money.format
  end

  def self.avg_prices
    self.includes(:orders).map do |e|
      num_orders = 0
      total_price = 0.0
      e.orders.each do |o|
        num_orders += 1
        total_price += o.total_price
      end
      [ e.id, e.orders.any? ? (total_price/num_orders).to_money.format : 'N/A' ]
    end
  end

  def self.drop_down_options
    self.all.map do |e|
      [e.name, e.id]
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employee }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  def last_30
    @employees = Employee.all
    render action: 'last_30'
  end

  def avg_prices
    respond_to do |format|
      format.json { render :json => Employee.avg_prices }
      format.html { }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :signup_date)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.includes(:employee).where('orders.created_at > ?', DateTime.now - 90.days).order('employees.signup_date DESC')
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:total_price, :num_units, :employee_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :signup_date %><br>
    <%= f.datetime_select :signup_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Signup date</th>
      <th></th>
      <th></th>
      <th></th>
      <th class='avg_price'>Average total price</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.signup_date %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td class='avg_price' id='avg_price_<%= employee.id %>'></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>
<%= link_to 'Show average total price', '#', id: 'show_avg_button' %>
<%= link_to 'Hide average total price', '#', id: 'hide_avg_button', class: 'avg_price' %>

app/views/employees/last_30.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Average 30 day price</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.avg_unit_price_30 %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Signup date:</strong>
  <%= @employee.signup_date %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BerkTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee %><br>
    <%= f.select(:employee_id, options_for_select(Employee.drop_down_options)) %>
  </div>

  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :num_units %><br>
    <%= f.number_field :num_units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Order Id</th>
      <th>Total price</th>
      <th>Created</th>
      <th>Num units</th>
      <th>Employee</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.total_price %></td>
        <td><%= order.created_at %></td>
        <td><%= order.num_units %></td>
        <td><%= order.employee.name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price %>
</p>

<p>
  <strong>Num units:</strong>
  <%= @order.num_units %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>